name: montirku_v1
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  google_maps_flutter: ^2.5.0
  location: ^5.0.0
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  multiselect_formfield: ^0.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.jpeg
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/3.jpg
    - assets/images/google.png
    - assets/images/Logo2.png
    - assets/images/notif.png
    - assets/images/12.png
    - assets/images/homeService.png
    - assets/images/booking3.png
    - assets/images/an chattinng.png
    - assets/images/13.jpeg
    - assets/images/my-location.png
    - assets/images/bank_card.png
    - assets/images/e-wallet.png
